os: osx
osx_image: xcode12
language: cpp

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update > /dev/null ;
      brew install qt5 cmake boost sqlite3 catch2;
      brew link --force qt ;
    fi
  - export core_count=$(nproc || echo 4) && echo core_count = $core_count

before_script:
  - export PATH=/usr/local/opt/qt5/bin:$PATH
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug ..

script:
  - cmake --build . --target Beertabs -- -j$core_count
  - cmake --build . --target functions_test -- -j$core_count
  - ctest functions_test

notifications:
  email:
    recipients:
      - minorsecond@gmail.com
    on_success: change
    on_failure: always