os: osx
osx_image: xcode12
language: cpp

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update ;
      brew install qt5 cmake boost sqlite3 catch2;
      brew link --force qt ;
    fi
    
before_script:
  - export PATH=/usr/local/opt/qt5/bin:$PATH
  - mkdir build
  - cd build
  - cmake -D CMAKE_BUILD_TYPE=Release ..
   
script:
  - cmake --build .
  - zip -r Beertabs.zip Beertabs.app
  
deploy:
  provider: releases
  file: "Beertabs.zip"
  skip_cleanup: true
  on:
    tags: true

env:
  global:
    secure: joMnpQMjTK4CDPbvmu0dPqaa/DbwP5PEZPMmfGngmqaQTq6GQ9rBXBBcFAPzCTPlnlJgyaQQj/hD3Igav+wB7mCxzCNykew5y6CdcuXTAZjh1Ywl2/6fY+wspIFTM9+MYK6XAve3OHNmqeK2OpiGowMzkhwTkV0KODSMvf9S0USJMFqjrFJ9JPN0Z8w9W7HLK2zKPzOGvuCec/Xu+OMGbXQqrp3MkyeNa4JqQ1HliFrDbEl3PYNyH9X/9dcI8vabnQE9p//TmAGNvAZ1iRqYM+HuTG+x6jjpizJsRmhVRcnkYrUF8C7QOQWJtQayWgQmn/n3R1BPU8OEOkgcG0fcPEuv6nbln0ewzX4m1l5xJEBGAMU3tj6VXOLBLFo+fhLqEJIJ1jhdKsBPmNUm6YHhK1YXCMVahNIlQ6lvlIq07BHBo4+lDZUONc4r2zfI1UjuxaXBkqB47uCuJCbLFg5YK09EuAtHznal4vxwccnREtjWCKmpVATYXdKOQ3YhyBEnkv3eShcDedESV+i6UVw81nvgQ0EEpPhJ26htDJWTByDv1bcTnkmTCI/03EsBtzSUAmA8hLsjnx3e649V9TJ061H9+WjdcKzp9WwYEcW8HfmfrFey+tVmohEVV5IhkCY1+ZTv9j4weD8ndusspUGp/Yo0tyKRzVFIOBLaOaF2KNQ=
