os: osx
osx_image: xcode12
language: cpp

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update ;
      brew install qt5 cmake boost sqlite3 catch2;
      brew link --force qt ;
    fi
    
before_script:
  - export PATH=/usr/local/opt/qt5/bin:$PATH
  - mkdir build
  - cd build
  - cmake -D CMAKE_BUILD_TYPE=Release ..
   
script:
  - cmake --build .
  - zip -r Beertabs.zip Beertabs.app
  
deploy:
  provider: releases
  api_key: "d388fcedbac566064186af2c55c2a3db9f89b423"
  file: "Beertabs.zip"
  skip_cleanup: true
  on:
    tags: true
