os: osx
osx_image: xcode12
language: cpp

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update ;
      brew install qt5 cmake boost sqlite3 ;
      brew link --force qt ;
    fi
   
script:
  - export PATH=/usr/local/opt/qt5/bin:$PATH
  - cmake -D CMAKE_BUILD_TYPE=Release .
